email_configuration.email_config.form:
  path: '/admin/config/system/email-config/form'
  defaults:
    _title: 'Email Configuration Form'
    _form: 'Drupal\email_configuration\Form\EmailConfigForm'
  requirements:
    _permission: 'administer email configuration form'
