<?php

/**
 * @file
 * Provides a wordbook entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function wordbook_theme(): array {
  return [
    'wordbook' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for wordbook templates.
 *
 * Default template: wordbook.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the wordbook information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_wordbook(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function wordbook_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish wordbook items.
      $storage = \Drupal::entityTypeManager()->getStorage('wordbook');
      $wordbook_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($wordbook_ids) as $wordbook) {
        $wordbook->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize wordbook items.
      $storage = \Drupal::entityTypeManager()->getStorage('wordbook');
      $wordbook_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($wordbook_ids) as $wordbook) {
        $wordbook->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function wordbook_user_predelete(UserInterface $account): void {
  // Delete wordbook items that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('wordbook');
  $wordbook_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($wordbook_ids)
  );
}
