<?php

/**
 * @file
 * Contains hook implementations.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function validate_entity_form_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if ($entity_type->id() === 'node' && $bundle === 'employee') {
    if (isset($fields['field_id'])) {
      // Add validation constraint for checking integer values.
      $fields['field_id']->addConstraint('UniqueInteger');
    }
  }
}
