integrate_weather_api.settings:
  type: config_object
  label: "Weather settings"
  mapping:
    api_key:
      type: string
      label: "API Key"
    base_url:
      type: string
      label: "Base URL"

block.settings.weather_display:
  type: block_settings
  label: "Weather Display settings"
  mapping:
    city:
      type: string
      label: "Name of the city to show weather details"
